# Generated by Django 6.0.2 on 2026-03-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('issue_title', models.CharField(max_length=255)),
                ('issue_description', models.TextField()),
                ('issue_type', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='issue_images/')),
                ('status', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=20)),
                ('admin_status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('working', 'Working'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
