# Generated by Django 6.0.2 on 2026-03-06 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='issue_title',
        ),
    ]
